### ISSUE TITLE
"failed to set up" error when using login credentials.

### ISSUE THREAD

**Issue by opwierde** [bajansen/home-assistant-frank_energie#110]
Recently installed and I can get the generic entities but when I login successfully I get the error "failed to set up"

**Comment by ljsquare** [comment]
Same here,
In my log this appears:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/__init__.py", line 36, in async_setup_entry
    raise Exception("No suitable sites found for this account")
Exception: No suitable sites found for this account

**Comment by Jeronimo1971** [comment]
Same here

**Comment by macdivernl** [comment]
Here too at initial config. Haven’t tried putting credentials in later, as all values appear correctly as mentioned in the (iOS) app.

= CONFIG =
Core v2024.6.4
Supervisor v2024.06.2
Operating System v12.4
Frontend v20240610.1
Frank Energie v3.0.0

**Comment by HMvdZijden** [comment]
No personal data possible.

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 11:24:50 (3 occurrences)
Last logged: 11:25:16

Error setting up entry xxx@gmail.com for frank_energie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/__init__.py", line 36, in async_setup_entry
    raise Exception("No suitable sites found for this account")
Exception: No suitable sites found for this account

**Comment by HA-Peet** [comment]
Same here....

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/__init__.py", line 36, in async_setup_entry
    raise Exception("No suitable sites found for this account")
Exception: No suitable sites found for this account

**Comment by daantimmer** [comment]
Same issue

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/__init__.py", line 36, in async_setup_entry
    raise Exception("No suitable sites found for this account")
Exception: No suitable sites found for this account
```

**Comment by eddysteurs** [comment]
me too

**Comment by oferinga** [comment]
Same for me

**Comment by tomdh76** [comment]
Same issue:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frank_energie/__init__.py", line 36, in async_setup_entry
    raise Exception("No suitable sites found for this account")
Exception: No suitable sites found for this account

In app account login works

**Comment by fabstar81** [comment]
Same issue here. Right after installation and configuration of credentials.
