### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by cascer1** [bajansen/home-assistant-frank_energie#14]
Hi,

Starting a few hours ago, the integration was unable to update my electricity price sensors because of an error:

<details>
<summary>error log</summary>

Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:164
Integration: Sensor (documentation, issues)
First occurred: 09:02:45 (1 occurrences)
Last logged: 09:02:45

Error while setting up frank_energie platform for sensor
```
Traceback (most recent call last):
  File "/config/custom_components/frank_energie/sensor.py", line 219, in _async_update_data
    data = await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://frank-graphql-prod.graphcdn.app/')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/frank_energie/sensor.py", line 223, in _async_update_data
    raise UpdateFailed(f"Fetching energy data failed: {error}") from error
homeassistant.helpers.update_coordinator.UpdateFailed: Fetching energy data failed: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://frank-graphql-prod.graphcdn.app/')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/frank_energie/sensor.py", line 140, in async_setup_platform
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Fetching energy data failed: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://frank-graphql-prod.graphcdn.app/')
```

</details>

One thing I've noticed is the URL that's being used. I thought the URL was `https://graphcdn.frankenergie.nl/`

**Comment by cascer1** [comment]
Closing the issue since it seems to have been caused by the Cloudflare outage earlier today.
